version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    hostname: rabbitmq.rabbitmq.docker
    networks:
      rabbitmq:
        aliases:
          - rabbitmq.rabbitmq.docker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  webapp:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    hostname: webapp.rabbitmq.docker
    networks:
      rabbitmq:
        aliases:
          - webapp.rabbitmq.docker
    ports:
      - "8000:8000"

  report:
    build:
      context: ./reports
      dockerfile: ./Dockerfile
    hostname: report.rabbitmq.docker
    networks:
      rabbitmq:
        aliases:
          - report.rabbitmq.docker

networks:
  rabbitmq:
    driver: bridge
